---
- name: Install Apache
  yum:
    name: "{{ item }}"
    state: "{{ apache_packages_state }}"
  with_items: "{{ apache_packages }}"

- name: Remove default config files
  shell: rm -f {{ apache_server_root }}/conf.d/*
  ignore_errors: yes

- name: Install config files - httpd.conf
  template:
    src: RedHat-httpd.conf.j2
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
  notify: restart httpd

- name: Create target dir for mod_jk
  file:
    state: directory
    dest: /opt/mod_jk
    owner: root
    group: root
    mode: 0755

- name: Copy over mod_jk installer
  unarchive:
    src: tomcat-connectors-1.2.46-src.tar.gz
    dest: /opt/mod_jk

- name: Copy over mod_jk compile script
  template:
    src: install_mod_jk.sh
    dest: /usr/local/bin/install_mod_jk.sh
    owner: root
    group: root
    mode: 0750

- name: Compile mod_jk
  command: /usr/local/bin/install_mod_jk.sh

- name: "Enabling SELinux booleans"
  shell: "/usr/sbin/setsebool -P {{ item }} 1"
  with_items:
    - httpd_can_network_connect
    - domain_can_mmap_files
  ignore_errors: true

- name: "Copy SELinux policy files"
  copy:
    src: "{{ item }}"
    dest: /etc/selinux/targeted/policy/
    owner: tomcat
    group: tomcat
  with_items:
    - contentcontroller.pp
    - contentcontroller.te
  when: ansible_distribution_major_version == "8"

- name: "Apply policy files"
  shell: "semodule -i /etc/selinux/targeted/policy/contentcontroller.pp"
  when: ansible_distribution_major_version == "8"