---

env: dev

# Use a local apt-cacher server to fetch packages
use_local_apt_cache: false
local_apt_cache_host: ""

noupgrade: false

# If you're running on an AWS instance and set this to true,
# ansible will install the AWS inspector agent for you
# setting this to true on a non-AWS ec2 box will have no effect.
aws_inspector: false

redhat_version: "7"