---

- name: Install Java
  include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Find Java home directory
  shell: readlink -f /usr/bin/javac | sed "s:/bin/javac::"
  register: java_readlink

- name: Set Java home directory
  set_fact:
    java_home: "{{ java_readlink.stdout }}"
  when: java_home is undefined

- name: Check to see if we already have a copy of the archive in place
  stat:
    path: "/etc/fapolicyd/fapolicyd.rules"
  register: fapolicy_enabled

# Not strictly related to Java, but we need java_home to have a value before we can inject this block
- name: "Configure fapolicyd to allow Content Controller"
  blockinfile:
    path: /etc/fapolicyd/fapolicyd.rules
    state: present
    insertbefore: '^# Only allow known ELF libs'
    block: |
      # Allow Ansible
      allow perm=open exe=/usr/libexec/openssh/sftp-server trust=1 : path=/usr/lib/libz.so.1.2.11 ftype=application/x-sharedlib trust=0
      allow perm=open exe=/usr/bin/sudo trust=1 : path=/usr/lib/libz.so.1.2.11 ftype=application/x-sharedlib trust=0
      allow perm=open exe=/usr/libexec/platform-python3.6 trust=1 : path=/usr/lib/libz.so.1.2.11 ftype=application/x-sharedlib trust=0
      allow perm=open exe=/usr/bin/dd trust=1 : all

      # Allow zlib for MySQL
      allow perm=open exe={{ java_home }}/jre/bin/java trust=1 : path=/usr/lib/libz.so.1.2.11 ftype=application/x-sharedlib trust=0
      allow perm=open exe={{ java_home }}/bin/java trust=1 : path=/usr/lib/libz.so.1.2.11 ftype=application/x-sharedlib trust=0

      # Allow Tomcat & Engine
      allow perm=open exe={{ java_home }}/jre/bin/java trust=1 : path=/opt/apache-tomcat-{{ tomcat_version }}/bin/bootstrap.jar ftype=application/java-archive trust=0
      allow perm=open exe={{ java_home }}/jre/bin/java trust=1 : path=/opt/apache-tomcat-{{ tomcat_version }}/bin/tomcat-juli.jar ftype=application/java-archive trust=0
      allow perm=open exe={{ java_home }}/jre/bin/java trust=1 : dir=/opt/apache-tomcat-{{ tomcat_version }}/lib/ all trust=0
      allow perm=open exe={{ java_home }}/jre/bin/java trust=1 : dir=/opt/apache-tomcat-{{ tomcat_version }}/webapps/ScormEngineInterface/WEB-INF/ all trust=0
      allow perm=open exe={{ java_home }}/jre/bin/java trust=1 : dir=/opt/apache-tomcat-{{ tomcat_version }}/work/Catalina/localhost/ScormEngineInterface/ ftype=application/x-java-applet trust=0
      allow perm=open exe={{ java_home }}/jre/bin/java trust=1 : dir=/opt/apache-tomcat-{{ tomcat_version }}/work/Catalina/localhost/ScormEngineInterface/ ftype=text/x-java trust=0

      # Allow Content Controller files
      allow perm=open exe={{ java_home }}/bin/java trust=1 : dir={{ cc_deploy_path }}/lib/ all trust=0
  when: ansible_os_family == 'RedHat' and fapolicy_enabled.stat.exists

- name: "Restart fapolicyd"
  service:
    name: "fapolicyd"
    state: "restarted"
  when: ansible_os_family == 'RedHat' and fapolicy_enabled.stat.exists