---

  - name: Fetch Java Version
    shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
    register: java_version
    ignore_errors: True

  - name: Check to see if java is up to date
    assert:
      that:
        java_version.stdout | version_compare('1.8.0_111', '>=')
    register: javaup2date
    ignore_errors: True

  - name: install java ppa (Ubuntu)
    apt_repository: repo='ppa:webupd8team/java'
    when: ansible_distribution == 'Ubuntu' and javaup2date|failed

  - name: Accept Oracle license (Ubuntu)
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    when: ansible_distribution == 'Ubuntu' and javaup2date|failed

  - name: install java8 (Ubuntu)
    apt: name=oracle-java8-installer state=latest update_cache=yes
    when: ansible_distribution == 'Ubuntu' and javaup2date|failed

  - name: Set Java 8 to default (Ubuntu)
    apt: name=oracle-java8-set-default state=latest update_cache=yes
    when: ansible_distribution == 'Ubuntu' and javaup2date|failed

  - name: set Java8 as default java (Ubuntu)
    file: src=/usr/lib/jvm/java-8-oracle  dest=/usr/lib/jvm/default-java state=link
    when: ansible_distribution == 'Ubuntu' and javaup2date|failed

  - name: install Debian Java CA certificates (Ubuntu)
    apt: name={{ item }} state=present
    with_items:
      - "ca-certificates-java"
    when: ansible_distribution == 'Ubuntu'

  - name: Java 8 | update networkaddress.cache.ttl in java.security (Ubuntu)
    lineinfile: dest=/usr/lib/jvm/java-8-oracle/jre/lib/security/java.security regexp='^networkaddress\.cache\.ttl' line='networkaddress.cache.ttl=30'
    when: ansible_distribution == 'Ubuntu'

  - name: Download Java (RedHat)
    command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"
    when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and javaup2date|failed

  - name: Unpack archive (RedHat)
    command: "tar -zxf {{java_archive}} -C {{download_folder}} creates={{java_name}}"
    when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and javaup2date|failed

  - name: Fix ownership (RedHat)
    file: state=directory path={{java_name}} owner=root group=root recurse=yes
    when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and javaup2date|failed

  - name: Make Java available for system (RedHat)
    command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'
    when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

  - name: Java 8 | update networkaddress.cache.ttl in java.security (RedHat)
    lineinfile: dest=/opt/jdk1.8.0_151/jre/lib/security/java.security regexp='^networkaddress\.cache\.ttl' line='networkaddress.cache.ttl=30'
    when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

  - name: Clean up (RedHat)
    file: state=absent path={{java_archive}}
    when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and javaup2date|failed
