---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  when: cc_db_host == "localhost"

- name: Install MySQL
  include_tasks: "install-{{ ansible_os_family }}.yml"
  when: cc_db_host == "localhost"

- name: Determine MySQL socket
  set_fact:
    mysql_socket: "{{ (ansible_os_family == 'Debian') | ternary('/var/run/mysqld/mysqld.sock', '/var/lib/mysql/mysql.sock') }}"
  when: cc_db_host == "localhost"

- name: Set root account password
  mysql_user: name=root password={{ mysql_root_password }} login_unix_socket={{ mysql_socket }} login_host=localhost priv=*.*:ALL,GRANT state=present
  when: cc_db_host == "localhost"

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  when: cc_db_host == "localhost"

- name: Create superuser account if the specified account isn't root
  mysql_user: login_user="root" login_password={{ mysql_root_password }} name={{ mysql_root_user }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT state=present
  when: mysql_root_user != "root" and cc_db_host == "localhost"
