---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install MySQL
  include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Set root account password
  mysql_user: name=root password={{ mysql_root_password }} priv=*.*:ALL,GRANT state=present

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Create superuser account if the specified account isn't root
  mysql_user: login_user="root" login_password={{ mysql_root_password }} name={{ mysql_root_user }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT state=present
  when: mysql_root_user != "root"
