---

  # We have to ensure that the tomcat group exists before we mount stuff
  - name: add group "tomcat"
    group: name=tomcat

  - name: add user "tomcat"
    user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
    become: true

  - name: Create directories as needed for tomcat
    file: path={{ item }} state=directory mode=0755 owner=tomcat group=tomcat
    with_items:
      - "{{ data_root }}"
      - "{{ content_root }}"
      - "{{ content_root }}/uploads"
      - "{{ content_root }}/courses"
      - "{{ content_root }}/xapi"
      - "{{ content_root }}/zips"
      - "{{ data_root }}/exports"
      - "{{ data_root }}/s3temp"
      - "{{ data_root }}/tmp"
      - "{{ data_root }}/reports"
