---
- name: "Set MySQL repo name for {{ mysql_version }}"
  set_fact:
    mysql_repo_version: "{{ (mysql_version == '5.7') | ternary('7-11', '7-1') }}"

- name: Fetch MySQL yum repo
  get_url:
    url: "https://dev.mysql.com/get/mysql{{ mysql_version | regex_replace('\\.', '') }}-community-release-el{{ mysql_repo_version }}.noarch.rpm"
    dest: "/tmp/mysql{{ mysql_version | regex_replace('\\.', '') }}-community-release-el{{ mysql_repo_version }}.noarch.rpm"
    mode: 0750

- name: Install MySQL repo
  yum:
    name: "/tmp/mysql{{ mysql_version | regex_replace('\\.', '') }}-community-release-el{{ mysql_repo_version }}.noarch.rpm"
    state: present

- name: Install pip
  package:
    name: python-pip
    state: latest
    update_cache: yes
