---
- name: Disable default MySQL repo (if using RHEL 8)
  shell: sudo dnf remove -y @mysql && sudo dnf module reset -y mysql && sudo dnf module disable -y mysql
  when: mysql_version == "5.7"

- name: Add MySQL repository (if using RHEL 8)
  copy:
    src: mysql-community.repo
    dest: /etc/yum.repos.d/mysql-community.repo
  when: mysql_version == "5.7"

- name: Disable mysql80 and enable mysql{{ mysql_version | regex_replace('\\.', '') }}
  # Can't use Ansible's built-in yum module because it doesn't support config-manager
  shell: yum config-manager --enable mysql{{ mysql_version | regex_replace('\\.', '') }}-community
  when: mysql_version == "5.7"
