# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rustici Software - Content Controller Deployment
email: info@scorm.com
description: > # this means to ignore newlines until "baseurl:"
  Deployment documentation for Rustici Software's Content Controller
baseurl: "/cc-deployment-public" # the subpath of your site, e.g. /blog
url: "https://rusticisoftware.github.io" # the base hostname & protocol for your site
twitter_username: "@rusticisoftware"
github_username: "RusticiSoftware"

# Build settings
markdown: kramdown
