---
  - import_tasks: roles/apache/handlers/main.yml

  - import_tasks: roles/mysql-config/handlers/main.yml

  - name: start contentcontroller
    action: service name=contentcontroller state=started
    notify: restart httpd

  - name: restart contentcontroller
    action: service name=contentcontroller state=restarted daemon_reload=yes
    notify: restart httpd

  - name: stop contentcontroller
    action: service name=contentcontroller state=stopped

  - name: stop cchealthcheck
    action: service name=cchealthcheck state=stopped daemon_reload=yes
