# This is a basic workflow to help you get started with Actions

name: CI

env:
  GITHUB_TOKEN: ${{secrets.RUSTICI_SYSTEMS_TOKEN}}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      # Automatically merge the stable branch into the development one
      - name: Merge master into development
        run: |
          git checkout --track origin/development
          git merge master --no-edit
          git remote set-url origin https://automation:${GITHUB_TOKEN}@github.com/RusticiSoftware/cc-deployment-public.git
          git push
